# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Aidan's Blog
first_name: Aidan
middle_name: Maxwell
last_name: Swope
email: aidanswope@gmail.com
description: Taming big, wiggly functions through optimization.

# Empty url & baseurl for Github Pages integration
url:  # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: false
footer_fixed: false

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# TODO
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: maxwells-daemons
gitlab_username:
twitter_username:
linkedin_username:
scholar_userid:
orcid_id:
medium_username:
quora_username:
publons_id:
research_gate_profile:
blogger_url:
work_url:
keybase_username:
wikidata_id:
dblp_url:

google_analytics: UA-173593414

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

permalink: /:year/:title/

# Pagination
pagination:
  enabled: true

# Comments
disqus_shortname: aidans-research-blog

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "distill"
      comments: true
      authors:
        - name: Aidan Swope
          url: "https://aidanswope.com/"
          affiliations:
            name:

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji

# Extras
github: [metadata]

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    true   # enables google analytics
enable_math:                true   # enables math typesetting (uses MathJax)
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.2.0"
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
medium_zoom:
  version: "1.0.6"
  integrity: "sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM="
