# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Aidan's Blog
first_name: Aidan
middle_name: Maxwell
last_name: Swope
email: aidanswope@gmail.com
description: Taming wiggly functions through optimization.

url: https://aidanswope.com
baseurl:

google_analytics: UA-173593414

# -----------------------------------------------------------------------------
# RSS Feed (https://github.com/jekyll/jekyll-feed)
# -----------------------------------------------------------------------------
author:
  name: Aidan Swope
  picture: /assets/misc/portrait.jpg

# -----------------------------------------------------------------------------
# Open Graph (display links to the page with a preview object on social media)
# -----------------------------------------------------------------------------
og_image: assets/icon/android-chrome-192x192.png

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: maxwells-daemons
gitlab_username:
twitter_username:
linkedin_username: aidan-swope
scholar_userid: vVzI7uwAAAAJ
orcid_id:
medium_username:
quora_username:
publons_id:
research_gate_profile:
blogger_url:
work_url:
keybase_username:
wikidata_id:
dblp_url:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
permalink: /:year/:title/

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "distill"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages"]
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - Dockerfile
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# Extras
github: [metadata]

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------
academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.2.0"
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
medium_zoom:
  version: "1.0.6"
  integrity: "sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM="
